name: ubuntu

on:
  push:
    branches: [ "master", "workflow" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      # 矩阵配置
      matrix:
        include:
          - qt_version: 6.2.4
            qt_arch: gcc_64
            modules: "qtwebengine qtnetworkauth qtmultimedia"

    env:
      BUILD_TYPE: Release
      BUILD_PATH: build
      assume: --release
      qt_target: 'desktop'
      qt_host: 'linux'
      archiveName: 'QSmartAssistant-${{ matrix.qt_version }}-${{ matrix.qt_arch }}'
      
    steps:
    - name: Install Qt
      if: 'true'
      # 使用外部action。这个action专门用来安装Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: ${{ matrix.qt_version }}
        host: ${{ env.qt_host }}
        target: ${{ env.qt_target }}
        arch: ${{ matrix.qt_arch }}
        install-deps: 'true'
        cache: 'true'
        aqtversion: '==3.1.*'
        modules: ${{ matrix.modules }}
        # tools: ${{ matrix.tools }}

    - uses: actions/setup-python@v5.1.0
      with:
        python-version: 3.10.11
    - uses: actions/checkout@v4
      with:
        fetch-depth: 1
        submodules: true
    - uses: actions/setup-node@v4
      with:
        node-version: "latest"
    - name: install dependency
      run: |
        cd scripts
        ./install_snowboy.sh
        ./install_openssl.sh
        ./install_sherpa_onnx.sh
        ./install_onnxruntime.sh
        ./install_rasa.sh
        ./install_neteasejs.sh
        cd ../Data
        wget https://github.com/k2-fsa/sherpa-onnx/releases/download/asr-models/sherpa-onnx-paraformer-zh-2024-03-09.tar.bz2
        tar xvf sherpa-onnx-paraformer-zh-2024-03-09.tar.bz2
        rm sherpa-onnx-paraformer-zh-2024-03-09.tar.bz2
        cp default_config.json config.json
        cp plugin_order_default.txt plugin_order.txt
    - name: build
      run: cmake -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} -DWAKEUP_DUILITE=OFF -DVAD_DUILITE=OFF -DWAKEUP_SNOWBOY=ON -DVAD_SILERO=ON -DNETEASE_USE_JS=ON -B ${{ env.BUILD_PATH }}
    - name: test
      run: |
        mkdir build_test && cd build_test
        cmake -DCMAKE_BUILD_TYPE=Debug -DWAKEUP_DUILITE=OFF -DVAD_DUILITE=OFF -DWAKEUP_SNOWBOY=ON -DVAD_SILERO=ON -DNETEASE_USE_JS=ON -DTEST=ON ..
        make -j8
        cd Debug/bin
        ./QSmartAssistant asrSherpa hassRegex
